---
title: "ADSC 1010 Project"
author: "Ivan Leonychev T00727314"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Data overview

```{r}
library(knitr)
library(ggplot2)
library(dplyr)
library(tidyr)
library(brew)

Battles <- read.csv(file = "ASOIAF_Battles.csv", header = TRUE)
Battles_info <- read.csv(file = "ASOIAF_Battles_Info.csv", header = TRUE)

Battles[1:5,]
glimpse(Battles)

Battles_info[1:5,]
glimpse(Battles_info)
```

# Battles

```{r}
ggplot(data = Battles, aes(year)) +
  geom_bar(fill = "darkgreen") +
  labs(title = "Barplot of Battles per year",
       x = "Year (AC)",
       y = "Count")

ggplot(data = Battles, aes(year, battle_name)) +
  geom_point() +
  labs(title = "Scatterplot of Battles per year with Names",
       x = "Year (AC)",
       y = "Battle Name")

ggplot(data = Battles, aes(attacker_allegiance, group = year, fill = year)) +
  geom_bar() +
  theme(axis.text.x = element_text(angle = 30, vjust = 0.5)) +
  scale_fill_gradient(low = "pink", high="red") +
  labs(title = "Barplot of Battles of Attacker Allegiance by year",
       x = "Attacker Allegiance",
       y = "Count")

ggplot(data = Battles, aes(defender_allegiance, group = year, fill = year)) +
  geom_bar() +
  theme(axis.text.x = element_text(angle = 30, vjust = 0.5)) +
  scale_fill_gradient(low = "lightblue", high="darkblue") +
  labs(title = "Barplot of Battles of Defender Allegiance by year",
       x = "Defender Allegiance",
       y = "Count")
```

# Houses

```{r}

```

